export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Features } from "./Features";
export { default as Info } from "./Info";
export { default as Global } from "./Global";
export { default as Footer } from "./Footer";
export { default as Subscription } from "./Subscription";
export { default as Plan } from "./Plan";
export { default as Testimonials } from "./Testimonials";
